webtalk_init -webtalk_dir /home/udagawa/projects/FPGA/Vivado/CNT60_ALL/CNT60_ALL.sim/sim_1/behav/xsim/xsim.dir/TEST_CNT60_ALL_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun  2 16:51:42 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c188a440-2148-43d8-ae0f-8dbd186a94b7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7f065d1233a5474697f1b5428adb0e8b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) CPU 1005M @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124372_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1125007329 -regid "" -xml /home/udagawa/projects/FPGA/Vivado/CNT60_ALL/CNT60_ALL.sim/sim_1/behav/xsim/xsim.dir/TEST_CNT60_ALL_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/udagawa/projects/FPGA/Vivado/CNT60_ALL/CNT60_ALL.sim/sim_1/behav/xsim/xsim.dir/TEST_CNT60_ALL_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/udagawa/projects/FPGA/Vivado/CNT60_ALL/CNT60_ALL.sim/sim_1/behav/xsim/xsim.dir/TEST_CNT60_ALL_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
