#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 29 14:20:22 JST 2018
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim T_ROT_7SEG_behav -key {Behavioral:sim_1:Functional:T_ROT_7SEG} -tclbatch T_ROT_7SEG.tcl -view /home/udagawa/projects/Vivado/ROT_7SEG/T_ROT_7SEG_behav.wcfg -log simulate.log
